### ISSUE TITLE
Manage Hotels

### ISSUE THREAD

**Issue by josueisaihs** [josueisaihs/hotels-manager#1]
# Task 1

- [x] Start project
   - [x] Clean main dir
   - [x] Create different config for each environment: `prod` and `test`
- [x] Fix it
   - [x] Django project
   - [x] Docker-files
- [x] Use queue worker
- [x] Add Auto-documentation
- [x] Create documentation about it

# Task 2

- [x]  Create model to store changes
- [x]  Create a new user model
- [x]  Implement permissions to differentiate non-staff users
- [x]  In the administration only reviewers can accept changes
- [x]  Customize the administration view
- [x]  Finish setting up nginx
- [x]  Make the GitHub Actions
- [x]  Document the admin
- [x]  Documentation about this
